        apiVersion: v1
        kind: Secret
        metadata:
          name: db-secret
        type: Opaque
        data:
          spring.datasource.username: dXNlcg== # Base64 encoded value user
          spring.datasource.password: dXNlcnBhc3M= # Base64 encoded value userpass