apiVersion: v1
kind: Service
metadata:
  name: k8s-ping
spec:
  selector:
    app: k8s-ping
  ports:
    - protocol: TCP
      port: 8089                 # La porta esposta all'interno del cluster
      targetPort: 8089         # La porta del container
